In [1]:
import pandas as pd

In [2]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [ ]:
### DATAFRAME ###

In [8]:
pd.DataFrame(data,index=[0,1,2,3])

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [10]:
df=pd.DataFrame(data,index=[0,1,2,3])

In [11]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [12]:
df.loc[1:3]

name  salary             mail_id addr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [13]:
df.iloc[2:3]

name  salary            mail_id addr
2  hitesh     300  hitesh@ineuron.ai  blr

In [14]:
df=pd.DataFrame(data,index=[4,5,6,7])

In [15]:
df

name  salary             mail_id addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  blr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [16]:
df=pd.DataFrame(data,index=['sudh','krish','hitesh','tulesko'])

In [17]:
df

name  salary             mail_id addr
sudh        sudh     100     sudh@ineuron.ai  blr
krish      krish     200    krish@ineuron.ai  blr
hitesh    hitesh     300   hitesh@ineuron.ai  blr
tulesko  tulesko     400  tulesko@ineuron.ai  mum

In [18]:
data1={'pf_nu': [234,45,54465,656], 
       'income_tax':[234,565,767,6778],
       'mobile_no':[23543,43543,454,5656],
       'courses':['ds','bigdata','web dev','blockchain']
      }

In [19]:
df1=pd.DataFrame(data1)

In [20]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454     web dev
3    656        6778       5656  blockchain

In [21]:
df

name  salary             mail_id addr
sudh        sudh     100     sudh@ineuron.ai  blr
krish      krish     200    krish@ineuron.ai  blr
hitesh    hitesh     300   hitesh@ineuron.ai  blr
tulesko  tulesko     400  tulesko@ineuron.ai  mum

In [22]:
#### CONCANTATION ###
pd.concat([df,df1])

name  salary             mail_id addr    pf_nu  income_tax  \
sudh        sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN   
krish      krish   200.0    krish@ineuron.ai  blr      NaN         NaN   
hitesh    hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN   
tulesko  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN   
0            NaN     NaN                 NaN  NaN    234.0       234.0   
1            NaN     NaN                 NaN  NaN     45.0       565.0   
2            NaN     NaN                 NaN  NaN  54465.0       767.0   
3            NaN     NaN                 NaN  NaN    656.0      6778.0   

         mobile_no     courses  
sudh           NaN         NaN  
krish          NaN         NaN  
hitesh         NaN         NaN  
tulesko        NaN         NaN  
0          23543.0          ds  
1          43543.0     bigdata  
2            454.0     web dev  
3           5656.0  blockchain

In [23]:
pd.concat([df,df1],axis=1)

name  salary             mail_id addr    pf_nu  income_tax  \
0            NaN     NaN                 NaN  NaN    234.0       234.0   
1            NaN     NaN                 NaN  NaN     45.0       565.0   
2            NaN     NaN                 NaN  NaN  54465.0       767.0   
3            NaN     NaN                 NaN  NaN    656.0      6778.0   
hitesh    hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN   
krish      krish   200.0    krish@ineuron.ai  blr      NaN         NaN   
sudh        sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN   
tulesko  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN   

         mobile_no     courses  
0          23543.0          ds  
1          43543.0     bigdata  
2            454.0     web dev  
3           5656.0  blockchain  
hitesh         NaN         NaN  
krish          NaN         NaN  
sudh           NaN         NaN  
tulesko        NaN         NaN

In [130]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1': [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3': ['blr' , 'blr' , 'blr' , 'mum']
    }

In [25]:
data3={'0': [234,45,54465,656], 
       '1':[234,565,767,6778],
       '2':[23543,43543,454,5656],
       '3':['ds','bigdata','web dev','blockchain']
      }

In [131]:
df2=pd.DataFrame(data2)

In [29]:
df3=pd.DataFrame(data3)

In [30]:
df3

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454     web dev
3    656        6778       5656  blockchain

In [132]:
df2

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [133]:
df2

0    1                   2    3
0     sudh  100     sudh@ineuron.ai  blr
1    krish  200    krish@ineuron.ai  blr
2   hitesh  300   hitesh@ineuron.ai  blr
3  tulesko  400  tulesko@ineuron.ai  mum

In [36]:

data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }


In [38]:
         
data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
         }
    

In [39]:
df4=pd.DataFrame(data4)

In [40]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [41]:
df5=pd.DataFrame(data5)

In [42]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [43]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [44]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [45]:
### MERGE ###
pd.merge(df4,df5,  how='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [46]:
pd.merge(df4,df5,  how='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [47]:
pd.merge(df4,df5,  how='right', on='emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [134]:

data6 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }


In [49]:
         
data7  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
         }
    

In [135]:
df6=pd.DataFrame(data6)

In [54]:
df7=pd.DataFrame(data7)

In [55]:
df7

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [136]:
df6

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [1]:
pd.merge(df6,df7,left_on='emp_id',right_on='emp_id', how='inner')

NameError: name 'pd' is not defined

In [3]:
pd.merge(df6,df7,left_on='emp_id',right_on='emp_id',how='inner')

NameError: name 'pd' is not defined

In [60]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }


In [3]:
pd.merge(df6,df7,left_on='emp_id',right_on='emp_id',how='inner')

NameError: name 'pd' is not defined

In [61]:
         
data9  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}

In [62]:
df8=pd.DataFrame(data8)

In [63]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [64]:
df9=pd.DataFrame(data9)

In [65]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56

In [66]:
pd.merge(df8,df9, on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [85]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
data11  = {'emp_id2' : [101,102,104,105],
          'salary2' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}


In [87]:
df10 = pd.DataFrame(data10)

In [88]:
df10

emp_id1  salary1  pf
0      101      234  23
1      102      345  34
2      103      200  56
3      104      400  78

In [89]:
df11=pd.DataFrame(data11)

In [90]:
df11

emp_id2  salary2  house_nu
0      101      234       345
1      102      345       345
2      104      200       345
3      105      878        56

In [91]:
df10=pd.DataFrame(data10,index=['a','b','c','d'])

In [92]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [94]:
df11=pd.DataFrame(data11,index=['a','b','d','e','f'])

ValueError: Shape of passed values is (4, 3), indices imply (5, 3)

In [84]:
df11=pd.DataFrame(data11,index='a','b','d','e','f')

SyntaxError: positional argument follows keyword argument (Temp/ipykernel_7396/85377018.py, line 1)

In [96]:
df_sales=pd.read_csv('C:\\Users\\Anulipsa pc\\Downloads\\FULL STACK DATA SCIENCE CLASS\\sales_data_final - Copy.csv')

In [97]:
df_sales.head()

order_id  order_date   ship_date       ship_mode    customer_name  \
0     AG-2011-2040  01-01-2011  01-06-2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   
2     HU-2011-1220  01-01-2011  01-05-2011    Second Class    Annie Thurman   
3  IT-2011-3647632  01-01-2011  01-05-2011    Second Class     Eugene Moren   
4    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [98]:
def profit_flag(a):
    if a>0:
        return 'positive'
    else:
        return 'negative'

In [99]:
profit_flag(-45)

'negative'

In [100]:
profit_flag(45)

'positive'

In [101]:
df_sales['flag_profit']=df_sales['profit'].apply(profit_flag)

In [102]:
df_sales.head()

order_id  order_date   ship_date       ship_mode    customer_name  \
0     AG-2011-2040  01-01-2011  01-06-2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   
2     HU-2011-1220  01-01-2011  01-05-2011    Second Class    Annie Thurman   
3  IT-2011-3647632  01-01-2011  01-05-2011    Second Class     Eugene Moren   
4    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [103]:
### length of customer name ####

In [105]:
df_sales['len_cust_name']=df_sales['customer_name'].apply(len)

In [106]:
df_sales.head()

order_id  order_date   ship_date       ship_mode    customer_name  \
0     AG-2011-2040  01-01-2011  01-06-2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   
2     HU-2011-1220  01-01-2011  01-05-2011    Second Class    Annie Thurman   
3  IT-2011-3647632  01-01-2011  01-05-2011    Second Class     Eugene Moren   
4    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [107]:
#### divide quantity ####

In [109]:
def quantity_flag(a):
    if a<10:
        return'low'
    elif a>10 and a<20:
        return 'medium'
    else:
        return 'high'

In [110]:
df_sales['flag_quantity']=df_sales['quantity'].apply(quantity_flag)

In [111]:
df_sales.head(20)

order_id  order_date   ship_date       ship_mode  \
0      AG-2011-2040  01-01-2011  01-06-2011  Standard Class   
1     IN-2011-47883  01-01-2011  01-08-2011  Standard Class   
2      HU-2011-1220  01-01-2011  01-05-2011    Second Class   
3   IT-2011-3647632  01-01-2011  01-05-2011    Second Class   
4     IN-2011-47883  01-01-2011  01-08-2011  Standard Class   
5     IN-2011-47883  01-01-2011  01-08-2011  Standard Class   
6      CA-2011-1510  01-02-2011  01-06-2011  Standard Class   
7     IN-2011-79397  01-03-2011  01-03-2011        Same Day   
8     ID-2011-80230  01-03-2011  01-09-2011  Standard Class   
9      IZ-2011-4680  01-03-2011  01-07-2011  Standard Class   
10    IN-2011-65159  01-03-2011  01-07-2011    Second Class   
11    IN-2011-65159  01-03-2011  01-07-2011    Second Class   
12  ES-2011-4869686  01-03-2011  01-07-2011  Standard Class   
13    IN-2011-33652  01-03-2011  01-09-2011  Standard Class   
14    ID-2011-80230  01-03-2011  01-09-2011  Standard Class   
15   MX-2011-160234  01-03-2011  01-07-2011  Standard Class   
16      IR-2011-770  01-03-2011  01-07-2011  Standard Class   
17    ID-2011-80230  01-03-2011  01-09-2011  Standard Class   
18    ID-2011-80230  01-03-2011  01-09-2011  Standard Class   
19    ID-2011-12596  01-03-2011  01-08-2011  Standard Class   

        customer_name      segment              state         country  market  \
0     Toby Braunhardt     Consumer        Constantine         Algeria  Africa   
1         Joseph Holt     Consumer    New South Wales       Australia    APAC   
2       Annie Thurman     Consumer           Budapest         Hungary    EMEA   
3        Eugene Moren  Home Office          Stockholm          Sweden      EU   
4         Joseph Holt     Consumer    New South Wales       Australia    APAC   
5         Joseph Holt     Consumer    New South Wales       Australia    APAC   
6     Magdelene Morse     Consumer            Ontario          Canada  Canada   
7         Kean Nguyen    Corporate    New South Wales       Australia    APAC   
8        Ken Lonsdale     Consumer           Auckland     New Zealand    APAC   
9    Lindsay Williams    Corporate             Ninawa            Iraq    EMEA   
10       Larry Blacks     Consumer   National Capital     Philippines    APAC   
11       Larry Blacks     Consumer   National Capital     Philippines    APAC   
12  Dorothy Dickinson     Consumer            England  United Kingdom      EU   
13      Dennis Pardue  Home Office            Sarawak        Malaysia    APAC   
14       Ken Lonsdale     Consumer           Auckland     New Zealand    APAC   
15   Stewart Visinsky     Consumer          Guatemala       Guatemala   LATAM   
16      Jas O'Carroll     Consumer               Yazd            Iran    EMEA   
17       Ken Lonsdale     Consumer           Auckland     New Zealand    APAC   
18       Ken Lonsdale     Consumer           Auckland     New Zealand    APAC   
19       Chris McAfee     Consumer  Nakhon Ratchasima        Thailand    APAC   

            region  ... sales quantity discount    profit shipping_cost  \
0           Africa  ...   408        2     0.00  106.1400         35.46   
1          Oceania  ...   120        3     0.10   36.0360          9.72   
2             EMEA  ...    66        4     0.00   29.6400          8.17   
3            North  ...    45        3     0.50  -26.0550          4.82   
4          Oceania  ...   114        5     0.10   37.7700          4.70   
5          Oceania  ...    55        2     0.10   15.3420          1.80   
6           Canada  ...   314        1     0.00    3.1200         24.10   
7          Oceania  ...   276        1     0.10  110.4120        125.32   
8          Oceania  ...   912        4     0.40 -319.4640        107.10   
9             EMEA  ...   667        4     0.00  253.3200         81.26   
10  Southeast Asia  ...   338        3     0.45 -122.8005         33.75   
11  Southeast Asia  ...   211        1     0.55  -70.3995         21.32   
12        

In [112]:
df_sales['square_quantity']=df_sales['quantity'].apply(lambda a:a**2)

In [113]:
df_sales.head()

order_id  order_date   ship_date       ship_mode    customer_name  \
0     AG-2011-2040  01-01-2011  01-06-2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   
2     HU-2011-1220  01-01-2011  01-05-2011    Second Class    Annie Thurman   
3  IT-2011-3647632  01-01-2011  01-05-2011    Second Class     Eugene Moren   
4    IN-2011-47883  01-01-2011  01-08-2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cust_name  flag_quantity square_quantity  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11            low              25  

[5 rows x 25 columns]

In [114]:
######## NUM PY ######

In [115]:
import numpy as np

In [116]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [117]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [119]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [120]:
l=[[1,2,3,4],[2,3,4,5]]

In [121]:
l[0][0]

1

In [122]:
l[0][1]

2

In [123]:
a=np.array([3,4,5,6],ndmin=3)

In [124]:
a

array([[[3, 4, 5, 6]]])

In [125]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [126]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
arr.ndim

2

In [128]:
np.random.randint(1,10,(4,4))

array([[5, 6, 2, 5],
       [6, 7, 8, 1],
       [1, 1, 7, 8],
       [8, 6, 6, 7]])

In [129]:
np.random.randint(1,10,(4,4,2))

array([[[9, 5],
        [2, 2],
        [9, 8],
        [5, 8]],

       [[4, 1],
        [9, 4],
        [6, 4],
        [5, 1]],

       [[2, 2],
        [4, 4],
        [7, 1],
        [1, 3]],

       [[2, 7],
        [6, 3],
        [2, 1],
        [3, 7]]])